const authors = [
	{
		name: 'Admin',
		image: 'placeholder',
		description: 'Official, cute and mysterious admin of AUA Confessions',
		fullDescription: '',
	},
	{
		name: 'Edgar Khanzadian',
		image: 'edgark',
		description: 'Developer',
		fullDescription: '',
		facebook: 'https://facebook.com/edgar.khanzadian',
		linkedin: '',
		github: 'https://github.com/edgarkhanzadyan',
		behance: '',
	},
	{
		name: 'Robert Gevorgyan',
		image: 'robertg',
		description: 'Developer',
		fullDescription: '',
		facebook: 'https://facebook.com/robert1999.g',
		linkedin: 'https://linkedin.com/in/rga15071999/',
		github: 'https://github.com/robgev',
		behance: '',
	},
	{
		name: 'Gevorg Hayrapetyan',
		image: 'gevorgh',
		description: 'UI/UX Designer',
		fullDescription: '',
		facebook: 'https://facebook.com/gev.whiskeyhouse',
		linkedin: 'https://linkedin.com/in/gevorghayrapetyan/',
		github: '',
		behance: 'https://behance.net/contact1d04',
	},
	{
		name: 'Aaron Sarkissian',
		image: 'aarons',
		description: 'Back-end Developer',
		fullDescription: '',
		facebook: 'https://facebook.com/aaronsarkissian',
		linkedin: '',
		github: 'https://github.com/aaronsarkissian',
		behance: '',
	},
	{
		name: 'Gurgen Hayrapetyan',
		image: 'gurgenh',
		description: 'Data Scientist',
		fullDescription: '',
		facebook: 'https://facebook.com/hayrapetyan.gurgen',
		linkedin: '',
		github: 'https://github.com/rasjonell',
		behance: '',
	},
];

export default authors;
