# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mobile_confessions' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mobile_confessions
  pod 'FirebaseMessaging'
  
  target 'mobile_confessionsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end