service: mobile-confessions

provider:
  name: aws
  runtime: nodejs6.10
  profile: ${file(./env.yml):PROFILE}
  region: ${file(./env.yml):REGION}
  stage: ${file(./env.yml):STAGE}
  memorySize: 128
  timeout: 5

  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:sendEmail
      Resource: "*"

functions:
  
  get_confession:
    handler: func/confessions.get_confession
    events:
      - http:
          path: confessions/get_confession
          method: post

  get_access_token:
    handler: func/confessions.get_access_token
    environment:
      FB_APP_ID: ${file(./env.yml):FB_APP_ID}
      FB_APP_SECRET: ${file(./env.yml):FB_APP_SECRET}
    events:
      - http:
          path: confessions/get_access_token
          method: get

  process_conf:
    handler: func/confessions.process_conf
    events:
      - http:
          path: confessions/process_conf
          method: post
    
  send_confession:
    handler: func/confessions.send_confession
    environment:
      SUPPORT_EMAIL: ${file(./env.yml):SUPPORT_EMAIL}
      ADMIN_EMAIL: ${file(./env.yml):ADMIN_EMAIL}
    events:
      - http:
          path: confessions/send_confession
          method: post

  send_feedback:
    handler: func/confessions.send_feedback
    events:
      - http:
          path: confessions/send_feedback
          method: post
